name: Deploy to Github Pages

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Build
        run: |
          npm i
          npm run build
          npm run export
        env:
          NOTION_ACCESS_TOKEN: ${{ secrets.NOTION_ACCESS_TOKEN }}
          WEDDING_GUESTS_DATABASE_ID: ${{ secrets.WEDDING_GUESTS_DATABASE_ID }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
